### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by Jack47** [cresset-template/cresset#32]
.env is below:

```
CUDA_VERSION=10.2
CUDNN_VERSION=8
PYTHON_VERSION=3.7
TORCH_CUDA_ARCH_LIST=8.0
PYTORCH_VERSION_TAG=v1.11.0
```
make build met error:

```
 > [internal] load metadata for docker.io/nvidia/cuda:11.2-cudnn8-devel-ubuntu18.04:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = docker.io/nvidia/cuda:11.2-cudnn8-devel-ubuntu18.04: not found
Makefile:55: recipe for target 'build' failed
```

seems nvidia changes image names?

**Comment by veritas9872** [comment]
@Jack47 Hello. It appears that you are trying to pull "cuda:11.2-cudnn8-devel-ubuntu18.04", which does not exist.
For some reason, the CUDA_VERSION variable has been set to `CUDA_VERSION =11.2`, which is unavailable.
Please set the variable `CUDA_VERSION =10.2` on your terminal and in all default variables.

**Comment by Jack47** [comment]
> @Jack47 Hello. It appears that you are trying to pull "cuda:11.2-cudnn8-devel-ubuntu18.04", which does not exist. For some reason, the CUDA_VERSION variable has been set to `CUDA_VERSION=11.2`, which is unavailable. Please set the variable `CUDA_VERSION=10.2` on your terminal and in all default variables.

yes, change it to 10.2 works, but I want to use 11.2 to build pytorch, seems nvidia changed it's naming convention: https://hub.docker.com/search?page=1&name=cudnn8&q=11.2+cudnn8, https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/unsupported-tags.md

**Comment by veritas9872** [comment]
The versioning system for CUDA was changed to follow semantic versioning as of CUDA 11.
To use the latest version of CUDA 11, please use `CUDA_VERSION=11.2.2`.

**Comment by Jack47** [comment]
> CUDA_VERSION=11.2.2

GREATE thanks, it works.
