### ISSUE TITLE
A minimal way to adopt the method in an existing project?

### ISSUE THREAD

**Issue by skandermoalla** [cresset-template/cresset#36]
Hello,

I came across this template when having trouble installing the environment of an existing project, given as a conda environment, but without more details about system dependencies. I wanted to build a portable environment with Docker but existing PyTorch images do not support my old GPU kernel, so I was looking for a way to compile Pytorch and Torchvision (CUDA enabled) from source in a Docker environment.

This project template addresses my problem and doubles down with best practices, however, I found it overwhelming to use/adapt it to my current project. Mainly because of the high complexity of building the environment that is transferred to the user (E.g. setting up the different env variables).

Is there a minimalist way to take this template and integrate it in an existing project?

Thanks!

**Comment by veritas9872** [comment]
@skandermoalla Hello! Thank you for being so interested in the project.
Currently, if only the PyTorch and TorchVision Python wheels are desired, the best thing would be to compile them and extract the wheels. 
As for integration with an existing project, the complexity of the previous project environment matters greatly.
Assuming that there are no compiled packages, simply identifying the necessary settings and requirements is enough.
For compiled libraries, please add  a `build-package` stage to the Dockerfile and copy the wheel to `/tmp/dist` in the `train-build` stage.

**Comment by veritas9872** [comment]
Other source files should not be affected since they are available inside the container automatically. Only components concerning the environment are affected.
After using `make exec` all project files should be visible in the `/opt/project` directory.

**Comment by veritas9872** [comment]
To get started with an existing repository, first clone Cresset into a separate folder, then copy the original repository, including the `.git` folder, into the Cresset working directory. Unnecessary files can be deleted as necessary.

**Comment by skandermoalla** [comment]
Thanks a lot @veritas9872 for the follow-up. [Here's](https://github.com/skandermoalla/bet-reproduction/tree/skander/installation) my current attempt at integrating Cresset into a project I'm working on. 
I've put the Cresset installation files in a separate directory called `installation` because we provide other installation methods there (e.g. a `conda` environment without docker to leverage the Apple M1 MPS backend.).
Could you have a quick look and spot if I'm braking some best practises from Cresset?
Thanks!

**Comment by veritas9872** [comment]
If placing the files in a separate directory, I would recommend changing the mount point for the /opt/project directory from the current working directory `.` to the project root as seen by the compose file, etc.g. `../..`. This will make sure that the project root is mounted properly at /opt/project inside the container.

**Comment by veritas9872** [comment]
As for the requirements, they all appear to have equivalent packages in PyPI, so I would recommend transitioning to pip installation.

**Comment by skandermoalla** [comment]
Indeed! I've done both steps and will close the issues. Thanks!
