### ISSUE TITLE
Conda dependencies in `train` stage

### ISSUE THREAD

**Issue by skandermoalla** [cresset-template/cresset#37]
Hello,

At the moment the template supports installing dependencies with`pip` in the `train` stage specified in  [pip-train.requirements.txt](https://github.com/cresset-template/cresset/blob/main/reqs/pip-train.requirements.txt). Is there a way to add `conda` dependencies as well?
[Best practices](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) are to install the `conda` dependencies first then the `pip` ones.

Thanks!

**Comment by skandermoalla** [comment]
A related question is how to integrate a project using an `environment.yml` file to manage dependencies on with `conda` and `pip` to the Cresset framework. I believe this could be showcased in a _How to migrate from an `environment.yml` file_ section in the README.

**Comment by veritas9872** [comment]
Hello. This is something that I struggled with in the early days of the project. One major issue I faced was that mixing conda and pip requirements caused reproducibility and overwriting issues. Are there any packages that cannot be installed via pip? If not, the best way would be to find pip equivalents of conda packages.

**Comment by veritas9872** [comment]
@skandermoalla If there are packages only available in `conda`, the best method would be to add the `environment.yaml` file to the `train-builds` stage. Please take the following steps.

1. Add `environment.yaml` to the `.dockerignore` file to allow Docker to read the environment file.
2. Assuming that the PYthon version, etc. are the same, add `conda create -y environment.yaml ` to the line above the `pip install`.

However, I have not tested using `conda`'s interactive features inside a Dockerfile and this may cause further issues. Unless the requirements are very specific, I would recommend converting them to `pip` packages, though this may be an initial nuisance.

**Comment by skandermoalla** [comment]
Thanks for the follow-up! I switched to having all the dependencies with `pip`, but I still believe Cresset would benefit from supporting `conda` train dependencies in thee future.

**Comment by veritas9872** [comment]
Installing via `conda` does not appear impossible, though it may encourage bad habits. I will consider implementing it as an option.
