### ISSUE TITLE
Issue with COMPOSE_PROJECT_NAME when username contains capital letters

### ISSUE THREAD

**Issue by skandermoalla** [cresset-template/cresset#41]
Hello,

The `Makefile` specifies `PROJECT = "${SERVICE}-${USR}"` which is used with the `-p` flag when using the compose project.

`COMPOSE_PROJECT_NAME` cannot take capital letters and usernames with capital letters will break the template.

e.g. 

```bash
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
        docker compose -p “train-Manel” up        --build -d
“train-Manel” is not a valid project name
make: *** [build] Error 1
```

**Comment by veritas9872** [comment]
Unfortunately, this is a limitation of Docker Compose, which cannot be helped.
See https://github.com/docker/compose/issues/1416 for details.

**Comment by veritas9872** [comment]
I will consider automatically converting variable names to lowercase inside the Makefile.

**Comment by veritas9872** [comment]
This issue has been solved. Please feel free to create another issue if any other problems occur.
