### ISSUE TITLE
git clone --job 에러

### ISSUE THREAD

**Issue by kboseong** [cresset-template/cresset#6]
git clone 명령어에 대하여 unknown option `jobs' 에러가 발생합니다.
혹시 해결방법이 있을까요?                                                                                                                                  

------                                                                                                                                                                     
 > [build-install 3/6] RUN git clone --recursive --jobs 0 https://github.com/pytorch/pytorch.git:                                                                          
#16 0.633 error: unknown option `jobs'                                                                                                                                     
#16 0.633 usage: git clone [<options>] [--] <repo> [<dir>]                                                                                                                 
#16 0.633 
#16 0.633     -v, --verbose         be more verbose
#16 0.633     -q, --quiet           be more quiet
#16 0.633     --progress            force progress reporting
#16 0.633     -n, --no-checkout     don't create a checkout
#16 0.633     --bare                create a bare repository
#16 0.633     --mirror              create a mirror repository (implies bare)
#16 0.633     -l, --local           to clone from a local repository
#16 0.633     --no-hardlinks        don't use local hardlinks, always copy
#16 0.633     -s, --shared          setup as shared repository
#16 0.633     --recursive           initialize submodules in the clone
#16 0.633     --recurse-submodules  initialize submodules in the clone
#16 0.633     --template <template-directory>
#16 0.633                           directory from which templates will be used
#16 0.633     --reference <repo>    reference repository
#16 0.633     --dissociate          use --reference only while cloning
#16 0.633     -o, --origin <name>   use <name> instead of 'origin' to track upstream
#16 0.633     -b, --branch <branch>
#16 0.633                           checkout <branch> instead of the remote's HEAD
#16 0.633     -u, --upload-pack <path>
#16 0.633                           path to git-upload-pack on the remote
#16 0.633     --depth <depth>       create a shallow clone of that depth
#16 0.633     --single-branch       clone only one branch, HEAD or --branch
#16 0.633     --separate-git-dir <gitdir>
#16 0.633                           separate git dir from working tree
#16 0.633     -c, --config <key=value>
#16 0.633                           set config inside the new repository
#16 0.633 
------
executor failed running [/bin/sh -c git clone --recursive --jobs 0 https://github.com/pytorch/pytorch.git]: exit code: 129
Makefile:23: recipe for target 'build-install' failed
make: *** [build-install] Error 1

**Comment by veritas9872** [comment]
어떤 설정으로 사용하셨는지 알려주신다면 도와드릴 수 있을 것 같습니다. 혹시 Makefile을 사용하셨나요?

**Comment by kboseong** [comment]
dockerfile에 아래내용을 추가하였습니다.

apt-get install -y software-properties-common
apt-get update
add-apt-repository ppa:git-core/ppa -y
apt-get update
apt-get install git -y

**Comment by kboseong** [comment]
같은 환경의 아래 커멘드에서도 에러가 발생합니다.

RUN --mount=type=cache,target=/opt/ccache \
    USE_CUDA=1 USE_CUDNN=1 \
    TORCH_NVCC_FLAGS=${TORCH_NVCC_FLAGS} \
    TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST} \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    python setup.py bdist_wheel -d /tmp/dist

에러 내용은 아래와 같습니다.
FAILED: caffe2/CMakeFiles/plan_executor_test.dir/core/plan_executor_test.cc.o

**Comment by veritas9872** [comment]
각 사용자의 local 환경은 모두 다르기 때문에 디버깅해드리기 어렵습니다.
다만, 에러 메시지로부터 봤을 때 NCCL을 설치하지 않은 것 같습니다.
