### ISSUE TITLE
CPU affinity can slow down torch.compile

### ISSUE THREAD

**Issue by rkindi** [cresset-template/cresset#96]
Thank you for making cresset! It really simplified a PyTorch 2.0 benchmarking setup I was working on.

One observation I had was that when I use `torch.compile` within a cresset container, the triton kernel compilation times are very slow because it seems the cpu affinity is being set somewhere during the pytorch build from source. I read in https://stackoverflow.com/a/15641148/21405443 that sometimes with the way some libraries are built, they will set the cpu affinity upon import. I suspect this is happening with `torch`. When using `torch.compile` to compile triton kernels, it uses [`AsyncCompile`](https://github.com/pytorch/pytorch/blob/master/torch/_inductor/codecache.py#L747-L794) which has a process pool and the process pool will fork with the cpu affinities set to a limited set of CPUs. So the pool's processes will get stuck to only using a small number of cpus despite a larger number being possibly available.

To work around it for my use case, I just run `os.system("taskset -p 0xff %d >/dev/null 2>&1" % os.getpid())` when my python script starts and it seems to be sufficient, but maybe it can be fixed in the cresset image build stage as well so people don't get surprised by the behavior. I did not figure out exactly what setting needs to be changed at the build stage to fix this.

My `.env` file:

```
GID=...
UID=...
GRP=janedoe
USR=janedoe
IMAGE_NAME=cresset:my_image
PROJECT_ROOT=/opt/project

# NVIDIA GPU Compute Capability (CCA) values may be found at https://developer.nvidia.com/cuda-gpus
CCA=8.0                          # Compute capability. CCA=8.6 for RTX3090 and A100.

# Used only if building PyTorch from source (`BUILD_MODE=include`).
# The `*_TAG` variables are used only if `BUILD_MODE=include`. No effect otherwise.
BUILD_MODE=include               # Whether to build PyTorch from source.
PYTORCH_VERSION_TAG=v2.0.0      # Any `git` branch or tag name can be used.
TORCHVISION_VERSION_TAG=v0.14.1

# General environment configurations.
LINUX_DISTRO=ubuntu              # Visit the NVIDIA Docker Hub repo for available base images.
DISTRO_VERSION=20.04             # https://hub.docker.com/r/nvidia/cuda/tags
CUDA_VERSION=12.0.1              # Must be compatible with hardware and CUDA driver.
CUDNN_VERSION=8                  # Only major version specifications are available.
PYTHON_VERSION=3.10              # Specify the Python version.
MKL_MODE=include                 # Enable MKL for Intel CPUs.
TZ=Asia/Seoul                    # Set the container timezone.

# Advanced Usage.
TARGET_STAGE=train               # Target Dockerfile stage. The `*.whl` files are available in `train-builds`.
```

**Comment by veritas9872** [comment]
@rkindi Thank you for the feedback! I have previously noticed issues with the CPU affinity, which is why Cresset currently does not set `KMP_AFFINITY=granularity=fine,compact,1,0`, which I mistakenly believed was a Docker issue.
Perhaps setting the `KMP_AFFINITY, `GOMP_CPU_AFFINITY`, `OMP_PROC_BIND`, and `OMP_SCHEDULE` values appropriately will be sufficient?

**Comment by veritas9872** [comment]
I hope that my answers have been helpful. I will be closing this issue for now but please feel free to reopen this issue if anything needs fixing!

**Comment by veritas9872** [comment]
@rkindi I have updated the image to use the recommended KMP_AFFINITY value and I found that it seems to work well in my environment. Although I haven't tried out `torch.compile` yet, I hope that the new configurations works well.
